### ISSUE TITLE
multiple discord accounts - not selectable

### ISSUE THREAD

**Issue by Ciannicay** [TheoKah/Enjin2Discord#1]
i got old accounts in discord that are still there but are not the one to be synced to enjin.
i cant get it to use an other than the first (based on the #xxxx number thats attached) account.
Please create a possibility to select which of the similar accounts is to be synced

**Comment by TheoKah** [comment]
Hi,

Where exactly do you want to select the account? Backend is usind unique id and are not based on discriminators so this is wierd.
