### ISSUE TITLE
Close to real-time updates?

### ISSUE THREAD

**Issue by PoisonShadows** [TheoKah/Enjin2Discord#2]
I've started using your Enjin/Discord role integration bot, and it does work... except that it only updates if I go in and hit 'save' in the admin area on the website and takes about 5 minutes to actually update in-game. I'm not worried about it taking 5 minutes to update, just that I want it to check my website automatically. I don't want to have to go in and click save every time I want people's ranks to update. Is there any way I can do this?

**Comment by TheoKah** [comment]
Sorry for late answer.

There was a problem with the bot and the bug you mentioned is now fixed.
I also fixed a problem where some enjin tags were ignored if you have a lot of users.

Bot will sync the ranks every 15 minutes or so. Feel free to contact me on discord if this is not the case: https://discord.gg/3ZSt2cq
